name: manabiplus
description: A new Flutter application.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.1.9+20
environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  analyzer:
  flutter:
    sdk: flutter
  cupertino_icons:
  provider:
  charts_flutter:
    git:
      url: https://github.com/google/charts.git
      path: charts_flutter
  firebase:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  image_picker:
  firebase_storage:
  flutter_launcher_icons:
  url_launcher:
  progress_state_button:

  package_info_plus: ^5.0.0
#  google_mobile_ads:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #   - images/a_dot_burr.jpeg
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/mitekara_logo_only.jpg"
  adaptive_icon_background: "#ffffff"
