// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf0wEB93gp2ekKKmgtBadiqIsy_6C-7Sk',
    appId: '1:389847026471:web:bf26ead17ccc9630a77702',
    messagingSenderId: '389847026471',
    projectId: 'manabiplus-4ba63',
    authDomain: 'manabiplus-4ba63.firebaseapp.com',
    storageBucket: 'manabiplus-4ba63.appspot.com',
    measurementId: 'G-T3CNR0LNK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeVwkp_b2loZNkhcUcwvTjir8csMBjgI0',
    appId: '1:389847026471:android:3179afe8511a9623a77702',
    messagingSenderId: '389847026471',
    projectId: 'manabiplus-4ba63',
    storageBucket: 'manabiplus-4ba63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK9SQNWI4UJ8xVMvSpDcAddWciqNLaOWU',
    appId: '1:389847026471:ios:4aae285e9188d9b0a77702',
    messagingSenderId: '389847026471',
    projectId: 'manabiplus-4ba63',
    storageBucket: 'manabiplus-4ba63.appspot.com',
    iosBundleId: 'com.mitekara.manabiplus1',
  );
}
